name: backend-nodejs-e-docker

services:
  backend-nodejs:
    build: .
    container_name: nodejs
    depends_on:
      - backend-postgres
  backend-postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - backend-nodejs-e-docker-postgres-data:/var/lib/postgresql/data

volumes:
  backend-nodejs-e-docker-postgres-data:
